#!/bin/bash
set -x

#install gradle
if [ ! -d $OPENSHIFT_DATA_DIR/gradle-2.10 ]
then
    cd $OPENSHIFT_DATA_DIR
    mkdir gradle
    wget http://services.gradle.org/distributions/gradle-2.10-bin.zip
    unzip gradle-2.10-bin.zip
    rm -f gradle-2.10-bin.zip
fi

rm -R $OPENSHIFT_DATA_DIR/jdk1.8.0_65