#!/bin/bash
set -x

#install gradle
if [ ! -d $OPENSHIFT_DATA_DIR/gradle-2.10 ]
then
    cd $OPENSHIFT_DATA_DIR
    mkdir gradle
    wget http://services.gradle.org/distributions/gradle-2.10-bin.zip
    unzip gradle-2.10-bin.zip
    rm -f gradle-2.10-bin.zip
fi

#Download Java8 If not already installed
if [ ! -d $OPENSHIFT_DATA_DIR/jdk1.8.0_65 ]; then
  wget -P $OPENSHIFT_DATA_DIR/ --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u65-b17/jdk-8u65-linux-x64.tar.gz
  tar -zxf $OPENSHIFT_DATA_DIR/jdk-8u65-linux-x64.tar.gz -C $OPENSHIFT_DATA_DIR
fi