#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
export PATH=/etc/alternatives/java_sdk_1.8.0/bin:$PATH
export JAVA_HOME="/etc/alternatives/java_sdk_1.8.0"
cd $OPENSHIFT_REPO_DIR
nohup java -jar build/libs/polls-1.0-SNAPSHOT.jar --spring.profiles.active=production --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} &