#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
export PATH=$OPENSHIFT_DATA_DIR/jdk1.8.0_65/bin:$PATH
export JAVA_HOME="$OPENSHIFT_DATA_DIR/jdk1.8.0_65"
cd $OPENSHIFT_REPO_DIR
nohup java -jar build/libs/polls-1.0-SNAPSHOT.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} &